# Generated by Django 2.1.2 on 2018-10-08 14:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_account_accountmeta_accounttransaction_systemapp_systemconfig_transferamount_transferrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmeta',
            name='account_id',
            field=models.ForeignKey(db_column='account_id', default=uuid.uuid4, max_length=36, on_delete=django.db.models.deletion.DO_NOTHING, to='bankapp.Account'),
        ),
        migrations.AlterUniqueTogether(
            name='accountmeta',
            unique_together={('account_id',)},
        ),
    ]
