# Generated by Django 2.1.2 on 2018-10-08 14:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_auto_20181008_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='account_id',
            field=models.ForeignKey(db_column='account_id', default=uuid.uuid4, max_length=36, on_delete=django.db.models.deletion.DO_NOTHING, to='bankapp.Account'),
        ),
        migrations.AlterField(
            model_name='transferamount',
            name='account_id',
            field=models.ForeignKey(db_column='account_id', default=uuid.uuid4, max_length=36, on_delete=django.db.models.deletion.DO_NOTHING, to='bankapp.Account'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='account_id',
            field=models.ForeignKey(db_column='account_id', default=uuid.uuid4, max_length=36, on_delete=django.db.models.deletion.DO_NOTHING, to='bankapp.Account'),
        ),
        migrations.AlterField(
            model_name='transferrequest',
            name='transfer_amount_id',
            field=models.ForeignKey(db_column='transfer_amount_id', default=uuid.uuid4, max_length=36, on_delete=django.db.models.deletion.DO_NOTHING, to='bankapp.TransferAmount'),
        ),
        migrations.AlterUniqueTogether(
            name='accounttransaction',
            unique_together={('account_id',)},
        ),
        migrations.AlterUniqueTogether(
            name='transferamount',
            unique_together={('account_id',)},
        ),
        migrations.AlterUniqueTogether(
            name='transferrequest',
            unique_together={('account_id', 'transfer_amount_id')},
        ),
    ]
